language: python
python: '3.6'
sudo: false
install:
- pip3 install ansible molecule testinfra molecule-gce google-auth
- ansible --version
- export GCE_CREDENTIALS_FILE=$(pwd)/application_default_credentials.json
- export GCE_SERVICE_ACCOUNT_FILE=$(pwd)/service_account_file.json
script:
- molecule create
- molecule converge
- molecule verify
env:
  global:
  - secure: AMoUDjPpKJQhD/FS3Z2stYxbenccyNs71NUiJb/nOO7noYx+OzeSSXNyksi2D/IIeCaCWdAwncTgP6KaAROhWfbXg4JI6EZY/CLTH0dHg3RbhYXJKP6QnvRpIN8yJVFwPBns12S+UmTGKSBvFnEQDt6vsagqN83RodlaBjv+GnNF4jwIuO/d35Y0Ews2edEpurNWE5EIYMxZrk9a2BbRHtkObMQshNykHd2Y0UPJAOFKToCmE28Eqej/djCDxpEDhUVYR8/6P02mQUS/cKQWWzasBdNXuaB3LGjX0lXiqaFnQg4Fl7QM4mkbGN08DDH7SZ/Ko3BmjtUbXKhIBUavPfeB3gnudQI0f6haWt6F+sA2L8akaoAg1Hb37iF5EaXxwGMxpN27QVcLmx51cHpvarUq7F4Th5vdDVx/MaOvETVaIURrhCgLwUwPQ3Q54IYKjWFr5/P/6jDYRYvG1nZXCkXYoTy+hcRh+cjq9rhz/vU9+FXD8vZ43oEj0ftxnQVQPwLMVE/cHK3eF7cLwmhkcVtDCW0SsOC1CbmJ2U8vrX7aZZr76eE0pJF+BCE0AGcewlsNUNhMi3Uqp43XJnFs+h/xGa8gj2rUTDrOzhDz415aROemTap171A5LE69bost7NjEXd4zaJ4alk7+LFh796gL/gUwKczl+zF/9kp4qk8=
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
after_script:
- molecule destroy
notifications:
  slack:
    secure: n60Z0/HkYLfNwCLj2Bi/kus6S/CFBisdArPBJrn9i4N/+sTWzzL/yGhufaPu3x4dkg/o8VZqD8Ir3ifL4OmOyxh1+kA2D8YxPgHJSn9eV3vcUhQX1lOxCT2FsKBBwDHMg/zDWtgJUJBqhy9Nn33srVn/A+QGpPViowoNHdlZR1nchfsos0MhALdA++TbJ/fhcckuKYovY/Bxfi+WxyfH6e/9lUyR0+biqVePMySBbwjAchoaR5nO+gvesRJtt7heNjm4JN4UQ2lClGleIn+8RnVVpRbS24m0PpcIqCU3D4lzLOVSTmZ6ZQD0tYySE/I6cxOddEd8HDtd52rwmoS2roLQbb2BLystrg9iLK1Iq1zOVHPTCqB7M5N60WWWmJAMDeWozTKkh34WWtNppstepXjZmIfESyIEAEJyo1UIN2nReIdCzkiCjAr+1YWsitBWrOjYMGV9HcnP2yrz/zRquzI+xnBBXJGyGrSdbID2Ia7OR7amPlE9QqijKHkJU4tdvDbd5ORu6oPjvmLJdGTzk9s7AnKWVpsKZfcOidflkF/fviUhPmOr0dMDQI03xaWdqtvfriwDrlCgC9uB1JiugrsfUAacxc3mGB1jVFr7QkE6kDMWX6ebUN5peNm374n9dWy7Pt1A4n4TxQiv0GPGOPSlNcwYQlB7/cknJ28NR0M=
