language: python
python: '3.6'
sudo: false
install:
- pip3 install ansible molecule testinfra molecule-gce google-auth
- ansible --version
script:
- molecule create
- molecule converge
- molecule verify
env:
  global:
  - secure: XFStvu4uC8cbU4Jf/svTlBEH5JuEK1acYgA+91BWpBs/PwXdl3yvYY/19owUcA/jOC1gxloO/FRk6giHhClo8E4u9VL/voJND3oh9jrnwEi3Hu4GGyxn9EwA8D1YQJr+5aY+1baLVSp3+ASQpl5NNqDVm+uNnyB6DC5pV5RuKrdUTB6FtJc/mFnCqHKhoH1HO+QAV02W1tio7YZWnBXRBJkWgi7TjxzTt31OTvJ4X+utgo0wMYTSJc0urdNFdJcsJKiXf36gNS4XBTPc/6mR31yQmjy4pL7qE8KuHA6H+A3E0sy28saTSAQopj8wdVBztdAvP8/mFrwjWudJlco9VLzntIFCdNmljLIQgTRp/CatVhv4gQY57wYSrD+wIX7egqpN8wxRYQ2JItrkJzqLpwhovV6do37FOwXoPtHUAoR3ZtHYV2QTkEPAmqi1OgmGK2Q5MFEsvC4SEc0fiD4f4nCRpo7LE4nZWlMVx5e9F7ssnCSnacCYnBQkTdjVbnLSybfwo7aqt7l8LygONyBKIKUQqGRchy6YsB9CQmUiw8yCEA0BSw0jbvvuoe7CRuCbmG7psUGBV+uHs+hCj5OM8lyuW1FuqRHWh6gIToxvyRztm8nMXNgmZmpUeyMAakeFjAYxFUrVbI6ZTkL5aQF8p46TYD7f+Eam4YX5q9sXXDk=
  - secure: M5TIt2m4IFjqsAiHdSYCNGPf3rIV8CcxgyfZs2G+qFnmiaQ6rLgXCf9IMEiYAU2+kTXziFMDeRwJ7iEcyDQlpfWVi8YcLYlGzHcp1WB/eqT23Qc2vZEXUJvaw+R9xCWTzj+/cYW4kmdHn/6ufdMnDw46MdbPv8QapfbEzCoDCFBuPrx8Z2yNYMtkl5wqufuf53AFjcSBcSI+A0iLFSm4USAIiTn6axrsRFvp25mstc5DfxjQX2GV2eKtaOCW2TdczwPVUUpX3ejZJQ2lqc3ZF5FXjjWmqqFXuQX9+eoI52nuILiRHDB+h7liUA0VEaCbJVGYqKOV/jn0RupXqFdAMMxexaBb4eFdXTCr9sJTzI/XRG7T4bxp50045vBOR3qj7dD9XwIj6firO5mtONZUK15sf3nhQRfEEA4n1/CLO+qKUMRZ0WBGw11qsHG8NPGEgf4sldEQSphxie0k5X/TGbtmcxqQVGqA31bMhwKs2mZnvDllMmP+A8IIkzsKnGF0kbYMZ/EfIWVQ+CqLzLRy23i/67fzquDOyRYUROBqjcULw8kk8xxwDZZ8TDNoP2OIdcc/40BJGCWF5qp6oYD6nStHFQxwb++/K/cGBueJ2dnaZOEuB3pVKuDuY/5AfBR8CbU4kXjYrYd4OioeZmIzgFZVD4PnwQYAYihC/kPD5Gk=
  - secure: AMoUDjPpKJQhD/FS3Z2stYxbenccyNs71NUiJb/nOO7noYx+OzeSSXNyksi2D/IIeCaCWdAwncTgP6KaAROhWfbXg4JI6EZY/CLTH0dHg3RbhYXJKP6QnvRpIN8yJVFwPBns12S+UmTGKSBvFnEQDt6vsagqN83RodlaBjv+GnNF4jwIuO/d35Y0Ews2edEpurNWE5EIYMxZrk9a2BbRHtkObMQshNykHd2Y0UPJAOFKToCmE28Eqej/djCDxpEDhUVYR8/6P02mQUS/cKQWWzasBdNXuaB3LGjX0lXiqaFnQg4Fl7QM4mkbGN08DDH7SZ/Ko3BmjtUbXKhIBUavPfeB3gnudQI0f6haWt6F+sA2L8akaoAg1Hb37iF5EaXxwGMxpN27QVcLmx51cHpvarUq7F4Th5vdDVx/MaOvETVaIURrhCgLwUwPQ3Q54IYKjWFr5/P/6jDYRYvG1nZXCkXYoTy+hcRh+cjq9rhz/vU9+FXD8vZ43oEj0ftxnQVQPwLMVE/cHK3eF7cLwmhkcVtDCW0SsOC1CbmJ2U8vrX7aZZr76eE0pJF+BCE0AGcewlsNUNhMi3Uqp43XJnFs+h/xGa8gj2rUTDrOzhDz415aROemTap171A5LE69bost7NjEXd4zaJ4alk7+LFh796gL/gUwKczl+zF/9kp4qk8=
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
after_script:
- molecule destroy
