language: python
python: '3.6'
sudo: false
install:
  - pip3 install ansible molecule testinfra molecule-gce google-auth
  - ansible --version
script:
  - molecule create
  - molecule converge
  - molecule verify
env:
  matrix:
    - GCE_CREDENTIALS_FILE="$(pwd)/application_default_credentials.json"
  global:
    - secure: FmmQEQUxynaNaX7R0u5aZanMrV+C4v4EcX2eVHvlwrr6gBXzF05/rgfR60rdNO577DsvveALGH2jc2DnPzvrhb1KBQDHzCVxTj3HFHjIRpqMWhVJfWAGvG6ou/B2PJ9MczkfBYwxrJqnP1CwPh700DhOyOhI/OPUJiKVjdd59c2bFzVYkWYv7WmowQbzLXqmmEohv89WAXnGcgedcJsMe3LuWXIJ7HmZ0QP3T9gpXYpdiy+9e7L4tQZONKdL/hZk1HSG0EntOkVRCSXuVMqGl/hFYWNDSYFNdIuXPPqXJOpKOJ4MxZ5XBo+9GYDQfxOZlJdPK9WCh1SoV0623dLxenpKXxK6+HkTBhx2kIZ14jzsimayvoADg4E+j+AqIg5UsYL+/fHnnUJD6MxszPiTzvYtsEoq2+plBsNUBK7Fj1knKZmyG8RVBQ0lgRcbr0BJrnoTlaFUwjXcBGLgKoXczMd2f8Tr+k1O496FfxcqQB4Gs1SANoa+xR63VQxUjUNRoCBrA3kcYYBQ/yk0ed4KyvfegbENrkMSmEZD0/ahiJMy+F6zoz2tGdyCgecBKBEqLKhQNTTzGnST9vqdfX7bkJFGVktS0vCS7i9iJaw2fGEk3Ag/eStAPakcpgKVKmhZMmw0sCDfiX9OfF92oEw7QksGSfGrWwdKOoLuWc0d6FE=
    - secure: sZrX+fgXYgtXngQcbN7i+FNibQhRJxZwzE4+iv8g4YVLoDwvtlOU4XM0OZ1ZkVm97IX3ehdjAl2c+PNnUNYIbaSHt9gAv9iroslnxsYhlhLT4mBRlkLOnTnyeDVDgce5P6/ETzao/i3jKlxTp/RBWx6rM1PvGUMd6x/B3zdKFwprTyMa7KitEtDcCgc5y8923YCHaJlaZuhLUvjessDRRIVKLt9W5atjHg6n6zpifV5kEX/Z47xxmBlPT7hCmuwRZV7QMnODMTJPvWtxKKvb4RstujFRaiYdZbVWl1T9wsWh47BUcScK0Pvss5Z0lL0zk7xdZDC2YRwzqXpx2n6/qjmNA39RvIAcRHhgkLfgmIMjw8o242StX03EwV4wOXeFjNwTKx+6InLa00ouxPaUZlc8IYkyBoWDTc4+zzPFCC1Nm0/nwKu0XNWm0epWNCxoGD8WgO1M7AWqbnX552WMqfSqggNX6yx/UhmveKGfMnDM54Sm+o5U8TTKAeyShAmuRgYdW+pueLUzInajAjt0TsP6vyQBdWPyousTMHksgzzEjq82iS6+iKTAfPKSq6v8CLJhWe+CWEpQ9sGfpFzN9cPJ05z7hYhyq985bHbYgVIkssB+eN1z0Xto2gAr08fLo7wucFOJOsRgP2cjqyj9xTIeGct6Old+Hu/hSRuDGKg=
    - secure: AMoUDjPpKJQhD/FS3Z2stYxbenccyNs71NUiJb/nOO7noYx+OzeSSXNyksi2D/IIeCaCWdAwncTgP6KaAROhWfbXg4JI6EZY/CLTH0dHg3RbhYXJKP6QnvRpIN8yJVFwPBns12S+UmTGKSBvFnEQDt6vsagqN83RodlaBjv+GnNF4jwIuO/d35Y0Ews2edEpurNWE5EIYMxZrk9a2BbRHtkObMQshNykHd2Y0UPJAOFKToCmE28Eqej/djCDxpEDhUVYR8/6P02mQUS/cKQWWzasBdNXuaB3LGjX0lXiqaFnQg4Fl7QM4mkbGN08DDH7SZ/Ko3BmjtUbXKhIBUavPfeB3gnudQI0f6haWt6F+sA2L8akaoAg1Hb37iF5EaXxwGMxpN27QVcLmx51cHpvarUq7F4Th5vdDVx/MaOvETVaIURrhCgLwUwPQ3Q54IYKjWFr5/P/6jDYRYvG1nZXCkXYoTy+hcRh+cjq9rhz/vU9+FXD8vZ43oEj0ftxnQVQPwLMVE/cHK3eF7cLwmhkcVtDCW0SsOC1CbmJ2U8vrX7aZZr76eE0pJF+BCE0AGcewlsNUNhMi3Uqp43XJnFs+h/xGa8gj2rUTDrOzhDz415aROemTap171A5LE69bost7NjEXd4zaJ4alk7+LFh796gL/gUwKczl+zF/9kp4qk8=
before_install:
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv google_compute_engine /home/travis/.ssh/
  - chmod 0600 /home/travis/.ssh/google_compute_engine
after_script:
  - molecule destroy
