language: python
python: '3.6'
sudo: false
install:
- pip3 install ansible molecule testinfra molecule-gce google-auth
- ansible --version
script:
- molecule create
- molecule converge
- molecule verify
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/application_default_credentials.json"
  global:
  - secure: XFStvu4uC8cbU4Jf/svTlBEH5JuEK1acYgA+91BWpBs/PwXdl3yvYY/19owUcA/jOC1gxloO/FRk6giHhClo8E4u9VL/voJND3oh9jrnwEi3Hu4GGyxn9EwA8D1YQJr+5aY+1baLVSp3+ASQpl5NNqDVm+uNnyB6DC5pV5RuKrdUTB6FtJc/mFnCqHKhoH1HO+QAV02W1tio7YZWnBXRBJkWgi7TjxzTt31OTvJ4X+utgo0wMYTSJc0urdNFdJcsJKiXf36gNS4XBTPc/6mR31yQmjy4pL7qE8KuHA6H+A3E0sy28saTSAQopj8wdVBztdAvP8/mFrwjWudJlco9VLzntIFCdNmljLIQgTRp/CatVhv4gQY57wYSrD+wIX7egqpN8wxRYQ2JItrkJzqLpwhovV6do37FOwXoPtHUAoR3ZtHYV2QTkEPAmqi1OgmGK2Q5MFEsvC4SEc0fiD4f4nCRpo7LE4nZWlMVx5e9F7ssnCSnacCYnBQkTdjVbnLSybfwo7aqt7l8LygONyBKIKUQqGRchy6YsB9CQmUiw8yCEA0BSw0jbvvuoe7CRuCbmG7psUGBV+uHs+hCj5OM8lyuW1FuqRHWh6gIToxvyRztm8nMXNgmZmpUeyMAakeFjAYxFUrVbI6ZTkL5aQF8p46TYD7f+Eam4YX5q9sXXDk=
  - secure: sZrX+fgXYgtXngQcbN7i+FNibQhRJxZwzE4+iv8g4YVLoDwvtlOU4XM0OZ1ZkVm97IX3ehdjAl2c+PNnUNYIbaSHt9gAv9iroslnxsYhlhLT4mBRlkLOnTnyeDVDgce5P6/ETzao/i3jKlxTp/RBWx6rM1PvGUMd6x/B3zdKFwprTyMa7KitEtDcCgc5y8923YCHaJlaZuhLUvjessDRRIVKLt9W5atjHg6n6zpifV5kEX/Z47xxmBlPT7hCmuwRZV7QMnODMTJPvWtxKKvb4RstujFRaiYdZbVWl1T9wsWh47BUcScK0Pvss5Z0lL0zk7xdZDC2YRwzqXpx2n6/qjmNA39RvIAcRHhgkLfgmIMjw8o242StX03EwV4wOXeFjNwTKx+6InLa00ouxPaUZlc8IYkyBoWDTc4+zzPFCC1Nm0/nwKu0XNWm0epWNCxoGD8WgO1M7AWqbnX552WMqfSqggNX6yx/UhmveKGfMnDM54Sm+o5U8TTKAeyShAmuRgYdW+pueLUzInajAjt0TsP6vyQBdWPyousTMHksgzzEjq82iS6+iKTAfPKSq6v8CLJhWe+CWEpQ9sGfpFzN9cPJ05z7hYhyq985bHbYgVIkssB+eN1z0Xto2gAr08fLo7wucFOJOsRgP2cjqyj9xTIeGct6Old+Hu/hSRuDGKg=
  - secure: AMoUDjPpKJQhD/FS3Z2stYxbenccyNs71NUiJb/nOO7noYx+OzeSSXNyksi2D/IIeCaCWdAwncTgP6KaAROhWfbXg4JI6EZY/CLTH0dHg3RbhYXJKP6QnvRpIN8yJVFwPBns12S+UmTGKSBvFnEQDt6vsagqN83RodlaBjv+GnNF4jwIuO/d35Y0Ews2edEpurNWE5EIYMxZrk9a2BbRHtkObMQshNykHd2Y0UPJAOFKToCmE28Eqej/djCDxpEDhUVYR8/6P02mQUS/cKQWWzasBdNXuaB3LGjX0lXiqaFnQg4Fl7QM4mkbGN08DDH7SZ/Ko3BmjtUbXKhIBUavPfeB3gnudQI0f6haWt6F+sA2L8akaoAg1Hb37iF5EaXxwGMxpN27QVcLmx51cHpvarUq7F4Th5vdDVx/MaOvETVaIURrhCgLwUwPQ3Q54IYKjWFr5/P/6jDYRYvG1nZXCkXYoTy+hcRh+cjq9rhz/vU9+FXD8vZ43oEj0ftxnQVQPwLMVE/cHK3eF7cLwmhkcVtDCW0SsOC1CbmJ2U8vrX7aZZr76eE0pJF+BCE0AGcewlsNUNhMi3Uqp43XJnFs+h/xGa8gj2rUTDrOzhDz415aROemTap171A5LE69bost7NjEXd4zaJ4alk7+LFh796gL/gUwKczl+zF/9kp4qk8=
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
after_script:
- molecule destroy
