language: python
python: '3.6'
sudo: false
install:
- pip3 install ansible molecule testinfra molecule-gce google-auth
- ansible --version
script:
- molecule create
- molecule converge
- molecule verify
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/application_default_credentials.json"
  global:
    - secure: lKZUbT5N7CV+0m4WKELZiiPA9PJupy/ynmuKfqB+mNPy5sVPiCBOTe+RtwAKNHYlYQanOYpDV1UWUtuxvv5TaRfR4kVxZom3R3p7uPmEdFbAnNwFgozBTLJOZaXJBJ6bYeXmg04XDHdYVfLSm3MAGINE2DJo5gDbMCDz//1FdG+qdMMgd3Oa0PI7He4gB9P94/D8mEVCKC9K7TTpNAylTz5UOAx61kGTEAqJMw3e+21lJo3WucOkH+LlTJp8t7yiioLHEvmnQG5tUvZTeuCEMrfvGVoyYnaXwi51UTp0SyBKOAcSRlXjZY9cTbx5RpdwyN4ulvISh4QV9W69FMIdVDP2iEdr8ydWT92q81Zk8vlZRlxh65Bbcr5y99PNECjvnK8B1l1wRi9llmPxONtczlAuIVvAjQGCswKWVCOKuYfdgzMw7Pos2TTgf85vD9xaBfhvdiYwEZMzaah37sYXYoSoSzaaFmELNCcap9nAVkipM47bRsoXrnYOUH5U506bbtW8uGmsmJq2iLStAQXTmpBGio0Wu1RaPR96pjRPYk6LGgunZVZDDu5csIJVwKn7NJNc3Y3AnJToU/5T7+Wb+8GrWaCA5k+Oe5wojue3iBXSKdmGw3LGmpGHEGqGE4eEL0YIRu7cep1B2WLgfsOfPSFFaB+X9u8U7lbMa/zSUQI=
    - secure: sZrX+fgXYgtXngQcbN7i+FNibQhRJxZwzE4+iv8g4YVLoDwvtlOU4XM0OZ1ZkVm97IX3ehdjAl2c+PNnUNYIbaSHt9gAv9iroslnxsYhlhLT4mBRlkLOnTnyeDVDgce5P6/ETzao/i3jKlxTp/RBWx6rM1PvGUMd6x/B3zdKFwprTyMa7KitEtDcCgc5y8923YCHaJlaZuhLUvjessDRRIVKLt9W5atjHg6n6zpifV5kEX/Z47xxmBlPT7hCmuwRZV7QMnODMTJPvWtxKKvb4RstujFRaiYdZbVWl1T9wsWh47BUcScK0Pvss5Z0lL0zk7xdZDC2YRwzqXpx2n6/qjmNA39RvIAcRHhgkLfgmIMjw8o242StX03EwV4wOXeFjNwTKx+6InLa00ouxPaUZlc8IYkyBoWDTc4+zzPFCC1Nm0/nwKu0XNWm0epWNCxoGD8WgO1M7AWqbnX552WMqfSqggNX6yx/UhmveKGfMnDM54Sm+o5U8TTKAeyShAmuRgYdW+pueLUzInajAjt0TsP6vyQBdWPyousTMHksgzzEjq82iS6+iKTAfPKSq6v8CLJhWe+CWEpQ9sGfpFzN9cPJ05z7hYhyq985bHbYgVIkssB+eN1z0Xto2gAr08fLo7wucFOJOsRgP2cjqyj9xTIeGct6Old+Hu/hSRuDGKg=
  - secure: AMoUDjPpKJQhD/FS3Z2stYxbenccyNs71NUiJb/nOO7noYx+OzeSSXNyksi2D/IIeCaCWdAwncTgP6KaAROhWfbXg4JI6EZY/CLTH0dHg3RbhYXJKP6QnvRpIN8yJVFwPBns12S+UmTGKSBvFnEQDt6vsagqN83RodlaBjv+GnNF4jwIuO/d35Y0Ews2edEpurNWE5EIYMxZrk9a2BbRHtkObMQshNykHd2Y0UPJAOFKToCmE28Eqej/djCDxpEDhUVYR8/6P02mQUS/cKQWWzasBdNXuaB3LGjX0lXiqaFnQg4Fl7QM4mkbGN08DDH7SZ/Ko3BmjtUbXKhIBUavPfeB3gnudQI0f6haWt6F+sA2L8akaoAg1Hb37iF5EaXxwGMxpN27QVcLmx51cHpvarUq7F4Th5vdDVx/MaOvETVaIURrhCgLwUwPQ3Q54IYKjWFr5/P/6jDYRYvG1nZXCkXYoTy+hcRh+cjq9rhz/vU9+FXD8vZ43oEj0ftxnQVQPwLMVE/cHK3eF7cLwmhkcVtDCW0SsOC1CbmJ2U8vrX7aZZr76eE0pJF+BCE0AGcewlsNUNhMi3Uqp43XJnFs+h/xGa8gj2rUTDrOzhDz415aROemTap171A5LE69bost7NjEXd4zaJ4alk7+LFh796gL/gUwKczl+zF/9kp4qk8=
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
after_script:
- molecule destroy
