language: python
python: '3.6'
sudo: false
install:
- pip3 install ansible molecule testinfra molecule-gce google-auth
- ansible --version
script:
- molecule create
- molecule converge
- molecule verify
env:
  global:
    - secure: hvuidySARJoxfTN5DQAOhlDolPL/0Hv70mg6TMqxO3DmM9yYtFdKBSF3nGTIfzRZNUf/OHGiZfMK+8gZgP2mn1e6ICnJXtHdcSCSQPckjGPYIrD1HPMOct8FDiNYGDbFp/Gj0pOVOgPzlri2ClmHJz+AWmCqiNKUqNT/15n1crA74CiilDgEvEkAmz7cmy/dY77+JsyYYnBM0hABJ1+qmyDMl6U43wVkMPkB0npqi+qoepC8RQAGDCh5nTD73lICwnQFeFF8uApCnFxe3u33p21R8fgBPo2EP/mbdT70xT4Fh88fWB7wYWv3ka+zwKt/x3xdqx33UImMHFvFGdd31AwlnJ7RDQ04vyQb5RP/v3R+eRo7wHgtwxglvqgSdZ4/vQvQj8AHb/E/NW9YOky185qvpsTer42sLElXyKjF6P9+doSHVdxTa8xpsEkKkPG6AWcYAM54ZYA/b0bVXMfz5qif58LhLsxb70lhWHsa/UQRT9BR37lNqp1Uh4BHR2OadWGnA7ZNfW9dd/fbC1nlxrt9OH9R+MQvUnYsp1BSYkFnAnjgpq6Q3Z4WFkLA4k3p/loQHuwiq6shHBywwrF7pOjH8X7oT3HMn5ea9ePd+pjWkZV4u+hbeOAxXSJm9Zoa6aNDP3gJPwL6c0T/Gz3UxM/TWVdoVrb8qXg1sir2ItY=
    - secure: qrqg1nG9ZXPF6lhS2wU5JFzyEU7LNyLiKGNM2y0krDgcytaX+Tq02e0mFNZi3FdNlXGd1qcv6qYb6wzjphNbPH1J1Q+hkd5I7s6u62yqMIb4QWLDBB8ERVQQ8oewj04p7JEkUdFzneTo1xY66Ycxtr8exp2KVuJRVNFuqfvkXXbR45FyOm6JuSJb3ij1AUEBqIdq7A5M/JH3YK3BjmHEBkZlRLHL7susI40BNRyYdTpTV8ttN7dkIbe3coNZbwaVd+n6B4DZiyDruM2p/zavDPl2Mh8vLcOahnTMNnj6bu2JLHdJjhwjMNmUfIOUFJdcKuQHJjVwvcZ5QAAbhqjSHht5EflqcnWmTBGJUipLcqR41YcdJzz9E2DAjhGmqY8ehLGo0tugpaBSwOHJig3iHwb4STnpSbMLb4lFbceA6TDSRT5KBCvZR4NBTCZz0TRoAlO90VqZWNCR8oR4O8lLiKq2PjntasWhgpl7/al+fkNCeyZQXLUm0oc4yM+VFU+Inn/JTB4U3f2qrNnV4s6RjFZsryQotBv0W0+loUJMhIVdGGFp8j7SSDiGnzk6CEXb1LjRcz837NJunJHW3lhIN73N5rcxv0Pw+mTyIv9gCdpU1VzqnX4t+4RFaZZflz8geiCkKwkq67qmHcn/yYFKGM+nQPBqBfw0APJl0k5+keo=
    - secure: AMoUDjPpKJQhD/FS3Z2stYxbenccyNs71NUiJb/nOO7noYx+OzeSSXNyksi2D/IIeCaCWdAwncTgP6KaAROhWfbXg4JI6EZY/CLTH0dHg3RbhYXJKP6QnvRpIN8yJVFwPBns12S+UmTGKSBvFnEQDt6vsagqN83RodlaBjv+GnNF4jwIuO/d35Y0Ews2edEpurNWE5EIYMxZrk9a2BbRHtkObMQshNykHd2Y0UPJAOFKToCmE28Eqej/djCDxpEDhUVYR8/6P02mQUS/cKQWWzasBdNXuaB3LGjX0lXiqaFnQg4Fl7QM4mkbGN08DDH7SZ/Ko3BmjtUbXKhIBUavPfeB3gnudQI0f6haWt6F+sA2L8akaoAg1Hb37iF5EaXxwGMxpN27QVcLmx51cHpvarUq7F4Th5vdDVx/MaOvETVaIURrhCgLwUwPQ3Q54IYKjWFr5/P/6jDYRYvG1nZXCkXYoTy+hcRh+cjq9rhz/vU9+FXD8vZ43oEj0ftxnQVQPwLMVE/cHK3eF7cLwmhkcVtDCW0SsOC1CbmJ2U8vrX7aZZr76eE0pJF+BCE0AGcewlsNUNhMi3Uqp43XJnFs+h/xGa8gj2rUTDrOzhDz415aROemTap171A5LE69bost7NjEXd4zaJ4alk7+LFh796gL/gUwKczl+zF/9kp4qk8=
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
after_script:
- molecule destroy
