---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: False
  no_log: no
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"

    ssh_port: 22
    ssh_user: "{{ lookup('env', 'USER') }}"
    ssh_identity_file: "{{ lookup('env', 'HOME') }}/.ssh/google_compute_engine"
#    ssh_identity_file: "~/.ssh/google_compute_engine"
  tasks:
    - shell: printenv
      register: result
    - name: debug
      debug:
        var: result
    - name: Create molecule instance(s)
      gcp_compute_instance:
        auth_kind: serviceaccount
        scopes:
          - https://www.googleapis.com/auth/compute
        name: "{{ item.name }}"
        project: "{{ lookup('env', 'GCE_PROJECT_ID') }}"
        zone: "{{ item.zone }}"
        machine_type: "{{ item.machine_type }}"
        service_account_file: "{{ lookup('env', 'GCE_SERVICE_ACCOUNT_FILE') }}"
        #        name: instance-travis
        #        project: terraform-project-272717
        #        zone: europe-west1-d
        #        machine_type: f1-micro
        #        service_account_file: ~/Downloads/terraform-project-272717-efadd6347988.json
        network_interfaces:
          - access_configs:
              - name: "External NAT"
                type: "ONE_TO_ONE_NAT"
        disks:
          - boot: yes
            auto_delete: yes
            initialize_params:
              source_image: "{{ item.image }}"
      register: server
      with_items: "{{ molecule_yml.platforms }}"

    - name: debug
      debug:
        var: server
    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.name }}",
          'address': "{{ item.networkInterfaces[0].accessConfigs[0].natIP }}",
          'user': "{{ ssh_user }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ ssh_identity_file }}", }
      with_items: "{{ server.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Create file if not exists
      file:
        path: "{{ molecule_instance_config }}"
        state: touch

    - name: Dump instance config
      copy:
        # NOTE(retr0h): Workaround for Ansible 2.2.
        #               https://github.com/ansible/ansible/issues/20885
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: check file content
      shell: "cat {{ molecule_instance_config }}"
      register: the_file

    - name: debug
      debug:
        var: instance_config_dict

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
      with_items: "{{ lookup('file', molecule_instance_config) | from_yaml }}"