#---
#dependency:
#  name: galaxy
#driver:
#  name: vagrant
#platforms:
#  - name: instance
#provisioner:
#  name: ansible
#verifier:
#  name: ansible
---
driver:
  name: gce
lint: yamllint
platforms:
  - name: instance-travis
    zone: europe-west1-d
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20170919
#    provider_raw_config_args:
#      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
provisioner:
  name: ansible
  lint: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
